name: CandyShop Build CI

on:
  # Still auto execute while push to master
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
    - '*.sh'
  # Manual trigger
  workflow_dispatch:
    inputs:
      branchType:
        description: 'Branch Type'     
        required: true
        type: choice
        options:
          - Dev branch check
          - Master branch check

jobs:
  Build:
    name: CI - Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.17.x']
    steps:       
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Target Branch
        run: |
          echo "Check: $BRANCH_TYPE"
          echo -e "Trigger Branch: \033[33m${GITHUB_REF#refs/heads/}\033[m"
        env:
          BRANCH_TYPE: ${{ github.event.inputs.branchType }}
      
      # Set up required dev env
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      # Building
      - name: Install dependencies
        run: npm install --global yarn && yarn

      - name: Install & Build core/types
        working-directory: ./core/types
        run: yarn && yarn build

      - name: Install & Build core/sdk
        working-directory: ./core/sdk
        run: yarn && yarn build
        
      - name: Install & Build core/ui 
        working-directory: ./core/ui
        run: yarn && yarn build
  
      - name: Build example
        run: yarn build
